
baseURL: "https://firstnameissoy.github.io/firstnameisoy.github.io/"
title: "My Hugo Site"
footnoteReturnLinkContents: "â†©"
permalinks:
  post: /:year/:month/:title/
params:
  Subtitle: "Hugo is Absurdly Fast!"
  AuthorName: "Jon Doe"
  GitHubUser: "spf13"
  ListOfFoo:
    - "foo1"
    - "foo2"
  SidebarRecentLimit: 5
  publishDir: docs
